### PR TITLE
Find proxyfmu using parent executable

### LINKED ISSUE #39: logging that proxies start
proxyfmu reports instances shutting down. Would be nice to also log when they start. As it takes some seconds before simulation starts due to starting the proxies, it would be good to see what's going on.

Here's an example when used in cosim-cli:

```
❯ .\cosim.exe run C:\path\to\conf\ -v
info: Using cache directory: "C:\\Users\\user\\AppData\\Local\\cosim"
info: 10% complete, t=0.100000
info: 20% complete, t=0.200000
info: 30% complete, t=0.300000
info: 40% complete, t=0.400000
info: 50% complete, t=0.500000
info: 60% complete, t=0.600000
info: 70% complete, t=0.700000
info: 80% complete, t=0.800000
info: 90% complete, t=0.900000
info: 100% complete, t=1.000000
[proxyfmu] Shutting down proxy for 'Spring::spring' done..
[proxyfmu] External proxy process for instance 'spring' returned with status 0
[proxyfmu] Shutting down proxy for 'Damper::damper' done..
[proxyfmu] External proxy process for instance 'damper' returned with status 0
[proxyfmu] Shutting down proxy for 'Mass::mass' done..
[proxyfmu] External proxy process for instance 'mass' returned with status 0
```

### LINKED ISSUE #40: Incorrectly assumes proxyfmu.exe in working directory
Currently the working directory must be equal to location of proxyfmu.exe. Running libcosim should know where to find proxyfmu. 

Works:
`C:\osp\cosim\bin> .\cosim.exe run C:\path\to\config\`

Fails:
`C:\osp\cosim> .\bin\cosim.exe run C:\path\to\config\`

### PR DESCRIPTION
**Pull request by markaren**
Closes #40 

Unsure if this works on linux without linker flags.

Also resolves #39

### CODE REVIEW

**Comment by ljamt** [comment]
Works well on windows. Unfortunately not on linux.
When running cosim-cli from a path different from where the executable is located is fails:

```
[proxyfmu] Booting FMU instance 'mass'..
terminate called after throwing an instance of 'boost::process::process_error'
  what():  execve failed: No such file or directory
Aborted
```

**Comment by markaren** [comment]
Then it might be the rdynamic linker option that we need, but the error suggests that it actually works, but it might not like the string format of the executable path.

**Comment by ljamt** [comment]
BTW, works well on linux if cosim-cli is called from its path.

**Comment by markaren** [comment]
Should work now. Also fixed an issue where proxyfmu would only work in a bash shell in windows. It never used the .exe postfix...

**Review by kyllingstad — APPROVED** [review]

**Pull request merged**
